// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLfD1FrRem2GGeubPLX18nHiH90k3MKDU',
    appId: '1:516228519041:web:05f7ba1c2ec4b7e18ba980',
    messagingSenderId: '516228519041',
    projectId: 'umerproject-c4ec7',
    authDomain: 'umerproject-c4ec7.firebaseapp.com',
    storageBucket: 'umerproject-c4ec7.appspot.com',
    measurementId: 'G-SYNJQ8GJVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbeb-z8xLjUur8GVtAIxu8QkV_HXpF5A',
    appId: '1:516228519041:android:3b4505b23284d9528ba980',
    messagingSenderId: '516228519041',
    projectId: 'umerproject-c4ec7',
    storageBucket: 'umerproject-c4ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKzsk2WkN1_PgdpqqWHn-o3W_PkZw49Q',
    appId: '1:516228519041:ios:27f50fc9b9da90b58ba980',
    messagingSenderId: '516228519041',
    projectId: 'umerproject-c4ec7',
    storageBucket: 'umerproject-c4ec7.appspot.com',
    iosBundleId: 'com.example.umer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKzsk2WkN1_PgdpqqWHn-o3W_PkZw49Q',
    appId: '1:516228519041:ios:27f50fc9b9da90b58ba980',
    messagingSenderId: '516228519041',
    projectId: 'umerproject-c4ec7',
    storageBucket: 'umerproject-c4ec7.appspot.com',
    iosBundleId: 'com.example.umer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLfD1FrRem2GGeubPLX18nHiH90k3MKDU',
    appId: '1:516228519041:web:09ac134c902617468ba980',
    messagingSenderId: '516228519041',
    projectId: 'umerproject-c4ec7',
    authDomain: 'umerproject-c4ec7.firebaseapp.com',
    storageBucket: 'umerproject-c4ec7.appspot.com',
    measurementId: 'G-6H3WQMHHTB',
  );
}
